QLThucTapSinh/QLThucTapSinh/Controllers/QLPersonController.cs
using QLThucTapSinh.Common;
using QLThucTapSinh.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLThucTapSinh.Controllers
{
    public class QLPersonController : Controller
    {
        SQLThucTapSinhEntities database = new SQLThucTapSinhEntities();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TTcanhan1()
        {
            var userName = Session["TenTk"].ToString();
            var findU = database.Users.Find(userName);
            var model = database.Person.Find(findU.PersonID);
            SetViewBagG();
            return View(model);
        }

        [HttpPost]
        public ActionResult TTcanhan1(string Password, string Newpassword)
        {
            var userName = Session["TenTk"].ToString();
            var model = database.Users.Find(userName);
            if (model.PassWord != MaHoaMd5.MD5Hash(Password))
            {
                ModelState.AddModelError("", "Mật khẩu không đúng.");

            }
            else
            {
                HomeController home = new HomeController();
                home.UpdateUser(model.PersonID, Newpassword);
            }
            SetViewBagG();
            var findP = database.Person.Find(model.PersonID);
            return View("TTcanhan1",findP);
        }

        [HttpPost]
        public ActionResult UpdatePerson(Person person)
        {
            var userName = Session["TenTk"].ToString();
            var model = database.Users.Find(userName);
            new Share().UpdatePerson(person);
            SetViewBagG();
            var findP = database.Person.Find(model.PersonID);
            return View("TTcanhan1", findP);
        }
        public void SetViewBag(string selectedID = null)
        {
            var list = database.Person.Where(x => x.RoleID == 2).ToList();
            List<Organization> Organ = new List<Organization>();
            foreach(var item in list)
            {
                var model = database.Organization.Find(item.CompanyID);
                Organ.Add(model);
            }
            SelectList OrganList = new SelectList(Organ, "ID", "Name");
            ViewBag.OrganList = OrganList;
        }

        public void SetViewBagS(string selectedID = null)
        {
            var list = database.Person.Where(x => x.RoleID == 3).ToList();
            List<Organization> Organ = new List<Organization>();
            foreach (var item in list)
            {
                var model = database.Organization.Find(item.SchoolID);
                Organ.Add(model);
            }
            SelectList SchoolList = new SelectList(Organ, "ID", "Name");
            ViewBag.SchoolList = SchoolList;
        }

        public void SetViewBagG(string selectedID = null)
        {
            SelectList GenGender = new SelectList( new[] {
                new {Text = "Nam", Value = true},
                new {Text = "Nữ", Value = false},
            }, "Value", "Text");
            ViewBag.GenGender = GenGender;
        }
        public ActionResult Testing(string personID = "ZXCDBUNQ")
        {
            var model = database.Person.Find(personID);
            SetViewBag();
            SetViewBagS();
            SetViewBagG();
            return View(model);
        }


    }
}

QLThucTapSinh/QLThucTapSinh/Views/QLPerson/CTTT.cshtml
<form class="modal-content animate" action="" method="post">
    <div class="imgcontainer">
        <span onclick="document.getElementById('id02').style.display='none'"
              class="close"
              title="Close Modal">&times;</span>
        <img class="circle1" src="~/img/hinhavatar.jpg" alt="" />
    </div>
    <div class="container">
        <label for="uname"><b>Họ</b></label>
        <br />
        <input type="text"
               placeholder="Nhập họ và tên lót"
               name="LastName"
               required />
        <br />
        <label for="uname"><b>Tên</b></label>
        <br />
        <input type="text"
               placeholder="Nhập tên"
               name="FirstName"
               required />
        <br />
        <label for="uname"><b>Giới tính</b></label>
        <br />
        <input type="text"
               placeholder="Enter Username"
               name="Gender"
               required />
        <br />
        <label for="uname"><b>Ngày sinh</b></label>
        <br />
        <input type="text"
               placeholder="Chọn ngày sinh"
               name="Birthday"
               class="datepicker"
               required />
        <br />
        <label for="uname"><b>Địa chỉ</b></label>
        <br />
        <input type="text"
               placeholder="Nhập địa chỉ"
               name="Address"
               required />
        <br />
        <label for="uname"><b>Số điện thoại</b></label>
        <br />
        <input type="text"
               placeholder="Nhập số điện thoại"
               name="Phone"
               required />
        <br />
        <label for="uname"><b>Email</b></label>
        <br />
        <input type="text"
               placeholder="Nhập Email"
               name="Email"
               required />
        <br />
        <label for="uname"><b>Ảnh</b></label>
        <br />
        <input type="text"
               placeholder="Chọn ảnh"
               name="Image"
               required />

        <label for="uname"><b>Tên trường</b></label>
        <br />
        <input type="text"
               placeholder="Enter Username"
               name="CompanyID"
               required />
        <br />
        <button type="submit" class="nut">Cập nhật thông tin</button>
    </div>
</form>

QLThucTapSinh/QLThucTapSinh/Views/QLPerson/TTCaNhan.cshtml
@{
    ViewBag.Title = "VC";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<link href="http://localhost:57770/Content/bootstrap.min.css" rel="stylesheet" />
<link type="text/css"
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Google+Sans:400,500,700" />
<link href="~/Content/Home/index3.css" rel="stylesheet" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<title>Document</title>

<body>
    <div class="container1">
        <div class="circle"></div>
        <h1>Thông tin của thực tập sinh</h1>
        <p class="thongtin">
            Họ và Tên : Trần Thành Nam <br />
            Giới Tính : Nam<br />
            Tuổi : 22<br />
            Địa Chỉ : An Khê, Quận Thanh Khê, TP Đà Nẵng<br />
            Phone : 0905865877 <br />
            Email : thnam98@gmail.com<br />
            School : Đại Học Duy Tân<br />
        </p>
        <h1 class="classh1">Xếp hạng các khóa học của thực tập sinh</h1>
        <div class="rank">
            <ul>
                <li>
                    <span class="number">1</span>
                    <span class="name">Khóa học lập trình C#</span>
                    <span class="points">100</span>
                    <span class="badge">
                        <i class="fa fa-trophy" aria-hidden="true"></i>
                    </span>
                </li>
                <li>
                    <span class="number">2</span>
                    <span class="name">Khóa học lập trình JavaScript từ A-Z</span>
                    <span class="points">95</span>
                    <span class="badge">
                        <i class="fa fa-trophy" aria-hidden="true"></i>
                    </span>
                </li>
                <li>
                    <span class="number">3</span>
                    <span class="name">Khóa học lập trình Master CSS</span>
                    <span class="points">85</span>
                    <span class="badge">
                        <i class="fa fa-trophy" aria-hidden="true"></i>
                    </span>
                </li>
                <li>
                    <span class="number">4</span>
                    <span class="name">Khóa học lập trình Python</span>
                    <span class="points">80</span>
                    <span class="badge">
                        <i class="fa fa-shield" aria-hidden="true"></i>
                    </span>
                </li>
                <li>
                    <span class="number">5</span>
                    <span class="name">Khóa học lập trình Java</span>
                    <span class="points">70</span>
                    <span class="badge">
                        <i class="fa fa-shield" aria-hidden="true"></i>
                    </span>
                </li>
            </ul>
        </div>
        <button onclick="document.getElementById('id01').style.display='block'"
                style="width:auto;"
                class="nut">
            Thay đổi mật khẩu
        </button>
        <button onclick="document.getElementById('id02').style.display='block'"
                style="width:auto;"
                class="nut1">
            Cập nhật thông tin
        </button>
    </div>

    <div id="id01" class="modal">
        <form class="modal-content animate" action="" method="post">
            <div class="imgcontainer">
                <span onclick="document.getElementById('id01').style.display='none'"
                      class="close"
                      title="Close Modal">&times;</span>
                <img class="circle1" src="~/img/hinhavatar.jpg" />
            </div>

            <div class="container">
                <label for="psw"><b>Mật khẩu</b></label>
                <br />
                <input type="password"
                       placeholder="Enter Password"
                       name="psw"
                       required />
                <br />
                <label for="psw"><b>Mật khẩu mới</b></label>
                <br />
                <input type="password"
                       placeholder="Enter New Password"
                       name="psw"
                       required />
                <br />
                <label for="psw"><b> Nhập lại mật khẩu mới</b></label>
                <br />
                <input type="password"
                       placeholder="Enter New Password"
                       name="psw"
                       required />
                <br />
                <button type="submit" class="nut">Thay đổi mật khẩu</button>

            </div>
        </form>
    </div>

    <div id="id02" class="modal">

        <form class="modal-content animate" action="" method="post">
            <div class="imgcontainer">
                <span onclick="document.getElementById('id02').style.display='none'"
                      class="close"
                      title="Close Modal">&times;</span>
                <img class="circle1" src="~/img/hinhavatar.jpg" alt="" />
            </div>
            <div class="container">
                <label for="uname"><b>Họ</b></label>
                <br />
                <input type="text"
                       placeholder="Nhập họ và tên lót"
                       name="LastName"
                       required />
                <br />
                <label for="uname"><b>Tên</b></label>
                <br />
                <input type="text"
                       placeholder="Nhập tên"
                       name="FirstName"
                       required />
                <br />
                <label for="uname"><b>Giới tính</b></label>
                <br />
                @Html.DropDownList("Gender", (IEnumerable<SelectListItem>)ViewBag.GenGender, null, htmlAttributes: new { @class = "gender", style = "width:10% ; margin: 8px 0;padding: 12px 20px; height:40px" })
                <br />
                <label for="uname"><b>Ngày sinh</b></label>
                <br />
                <input type="text"
                       placeholder="Chọn ngày sinh"
                       name="Birthday"
                       class="datepicker"
                       required />
                <br />
                <label for="uname"><b>Địa chỉ</b></label>
                <br />
                <input type="text"
                       placeholder="Nhập địa chỉ"
                       name="Address"
                       required />
                <br />
                <label for="uname"><b>Số điện thoại</b></label>
                <br />
                <input type="text"
                       placeholder="Nhập số điện thoại"
                       name="Phone"
                       required />
                <br />
                <label for="uname"><b>Email</b></label>
                <br />
                <input type="text"
                       placeholder="Nhập Email"
                       name="Email"
                       required />
                <br />
                <label for="uname"><b>Ảnh</b></label>
                <br />
                <input type="text"
                       placeholder="Chọn ảnh"
                       name="Image"
                       id = "xFilePath"
                       class="imageCV"
                       required />
                <a id="SelectImage" onclick="BrowseServer()" href="#">Chọn ảnh</a>
                <br />
                <label for="uname"><b>Tên Công ty</b></label>
                @*<br />
        @Html.DropDownList("CompanyID", (IEnumerable<SelectListItem>)ViewBag.CompanyList, null, new { @class = "form-control" })
        <br />*@
                <label for="uname"><b>Tên trường</b></label>
                <br />
                <input type="text"
                       placeholder="Enter Username"
                       name="CompanyID"
                       required />
                <br />
                <button type="submit" class="nut">Cập nhật thông tin</button>
            </div>
        </form>
    </div>
</body>
<script src="https://kit.fontawesome.com/e00695e77f.js"
        crossorigin="anonymous"></script>
<script src="../Scripts/HomeControl/jquery-3.4.1.min.js"></script>
<script src="http://localhost:57770/Scripts/popper.min.js"></script>
<script src="http://localhost:57770/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<script src="../Scripts/HomeControl/index.js"></script>

QLThucTapSinh/QLThucTapSinh/Views/QLPerson/TTcanhan1.cshtml
@model QLThucTapSinh.Models.Person
@{
    ViewBag.Title = "VC";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<link href="http://localhost:57770/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/Home/index3.css" rel="stylesheet" />
<link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Google+Sans:400,500,700" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<title>Document</title>

<body>
    <div class="container1">
        <h1 class="information">THÔNG TIN CÁ NHÂN</h1>
        <img class="circle1" src="@Model.Image" />
        <div class="my-birday">
            <div class="item">
                <span class="text-list"> Họ Và Tên:</span>
                <span class="text-list1">@Model.LastName @Model.FirstName</span>
            </div>
            <div class="item">
                <span class="text-list"> Birthday:</span>

                <span class="text-list1">@Html.FormatValue(@Model.Birthday, "{0:dd/MM/yyyy}")</span>
            </div>
            <div class="item">
                <span class="text-list"> Giới tính:</span>
                @if (Model.Gender == true)
                {
                    <span class="text-list1">Nam</span>
                }
                else
                {
                    <span class="text-list1">Nữ</span>
                }

            </div>
            <div class="item">
                <span class="text-list">Địa Chỉ:</span>
                <span class="text-list1">@Model.Address</span>
            </div>
            <div class="item">
                <span class="text-list">Số điện thoại:</span>
                <span class="text-list1">@Model.Phone</span>
            </div>
            <div class="item">
                <span class="text-list">Email:</span>
                <span class="text-list1">@Model.Email</span>
            </div>

        </div>
        <button onclick="document.getElementById('id01').style.display='block'"
                style="width:auto;"
                class="nut">
            Thay đổi mật khẩu
        </button>
        <button onclick="document.getElementById('id02').style.display='block'"
                style="width:auto;"
                class="nut1">
            Cập nhật thông tin
        </button>
    </div>

    <div id="id01" class="modal">
        <form class="modal-content animate" action="" method="post">
            @using (Html.BeginForm("TTcanhan1", "QLPerson", FormMethod.Post))
            {
                <div class="imgcontainer">
                    <span onclick="document.getElementById('id01').style.display='none'"
                          class="close"
                          title="Close Modal">&times;</span>
                </div>

                <div class="container">
                    <label for="psw"><b>Mật khẩu</b></label>
                    <br />
                    <input type="password"
                           placeholder="Enter Password"
                           name="Password"
                           required />
                    <br />
                    <label for="psw"><b>Mật khẩu mới</b></label>
                    <br />
                    <input type="password"
                           placeholder="Enter New Password"
                           name="Newpassword"
                           id="Newpassword"
                           required />
                    <div id="toggle" onclick="showHide();">
                        <i class="fa fa-eye" aria-hidden="true"></i>
                    </div>
                    <br />
                    <label for="psw"><b> Nhập lại mật khẩu mới</b></label>
                    <br />
                    <input type="password"
                           placeholder="Enter New Password"
                           name="psw"
                           id="passwordAgain"
                           required />
                    <div id="toggle2" onclick="showHide2();">
                        <i class="fa fa-eye" aria-hidden="true"></i>
                    </div>
                    <br />
                    <button type="submit" class="nut">Thay đổi mật khẩu</button>

                </div>
            }

        </form>
    </div>

    <div id="id02" class="modal">
        <form class="modal-content animate" action="UpdatePerson" method="post">
            <div class="imgcontainer">
                <span onclick="document.getElementById('id02').style.display='none'"
                      class="close"
                      title="Close Modal">&times;</span>
                <img class="circle1" src="@Model.Image" alt="" />
            </div>

            @Html.HiddenFor(model => model.PersonID)
            <div class="container">
                <div class="hvt">

                    <h3 class="Name">Họ:</h3>

                    <input type="text"
                           value="@Model.LastName"
                           name="LastName"
                           required
                           style="width: 20% !important;margin-left: 32px !important;" />
                    <h3 class="Name">Tên:</h3>


                    <input class="formnhap" type="text"
                           value="@Model.FirstName"
                           name="FirstName"
                           required style="width: 20% !important;margin-left: 32px !important;" />

                </div>
                <div class="hvt">
                    <label for="uname"><h3 class="Name">Giới tính:</h3></label>

                    @Html.DropDownList("Gender", (IEnumerable<SelectListItem>)ViewBag.GenGender, "--Select Gender--", htmlAttributes:
                   new { @class = "gender ", style = "width:19.8% ; margin-top: 7px ; margin-left:-12px;padding: 1px 0px; height:40px" })

                    <label for="uname"><h3 class="Name">Ngày sinh:</h3></label>

                    <input type="text"
                           name="Birthday"
                           class="datepicker"
                           value="@Model.Birthday"
                           style="margin-left: -6px;width:20% !important;"
                           required />

                </div>
                <div class="hvt">
                    <label for="uname"><h3 class="Name">Địa chỉ:</h3></label>

                    <input type="text"
                           value="@Model.Address"
                           name="Address"
                           required
                           style="width:48% !important" />
                </div>
                <div class="hvt">
                    <label for="uname"><h3 class="Name">Số điện thoại</h3></label>

                    <input type="text"
                           value="@Model.Phone"
                           name="Phone"
                           required
                           style="width:44.4% !important" />
                </div>
                <div class="hvt">
                    <label for="uname"><h3 class="Name">Email</h3></label>

                    <input type="text"
                           value="@Model.Email"
                           name="Email"
                           required
                           style="width:49.5% !important" />
                </div>
                <div class="hvt">
                    <label for="uname"><h3 class="Name">Ảnh</h3></label>
                    <br />
                    <input type="text"
                           value="@Model.Image"
                           name="Image"
                           id="xFilePath"
                           class="imageCV"
                           style="width:44% !important"
                           required />
                    <a id="SelectImage" onclick="BrowseServer()" style="position: relative;top: 25px" href="#">Chọn ảnh</a>
                </div>
                <button type="submit" style="margin-top: 30px" @*class="nut"*@>Cập nhật thông tin</button>

            </div>
        </form>
    </div>
</body>
<script src="https://kit.fontawesome.com/e00695e77f.js"
        crossorigin="anonymous"></script>
<script src="../Scripts/HomeControl/jquery-3.4.1.min.js"></script>
<script src="http://localhost:57770/Scripts/popper.min.js"></script>
<script src="http://localhost:57770/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<script src="../Scripts/HomeControl/index1.js"></script>

QLThucTapSinh/QLThucTapSinh/Views/QLPerson/Testing.cshtml
@model QLThucTapSinh.Models.Person

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Person</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PersonID)

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.DropDownList("Gender", (IEnumerable<SelectListItem>)ViewBag.GenGender, null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.CompanyID, "CompanyID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyID", (IEnumerable<SelectListItem>)ViewBag.OrganList, null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SchoolID, "SchoolID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SchoolID", (IEnumerable<SelectListItem>)ViewBag.SchoolList, null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SchoolID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>