QLThucTapSinh/QLThucTapSinh/Controllers/QLInternController.cs
using PagedList;
using QLThucTapSinh.Common;
using QLThucTapSinh.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using Excel = Microsoft.Office.Interop.Excel;

namespace QLThucTapSinh.Controllers
{
    public class QLInternController : Controller
    {
        // GET: QLIntern
        SQLThucTapSinhEntities database = new SQLThucTapSinhEntities();

        public ActionResult Index1()
        {
            var model1 = listIShip();
            var companyID = Session["CompanyID"].ToString();
            var listIn = (from a in database.Person
                          join b in database.Intern on a.PersonID equals b.PersonID into joinl1
                          from j in joinl1.DefaultIfEmpty()
                          join f in database.Organization on a.SchoolID equals f.ID into join4
                          from p in join4.DefaultIfEmpty()
                          where a.CompanyID == companyID && a.RoleID == 5 && j.InternshipID == null
                          select new InternDatabase()
                          {
                              PersonID = a.PersonID,
                              FullName = a.LastName + " " + a.FirstName,
                              Birthday = a.Birthday,
                              Gender = a.Gender,
                              Address = a.Address,
                              Phone = a.Phone,
                              Email = a.Email,
                              Image = a.Image,
                              CompanyID = a.CompanyID,
                              InternshipID = j.InternshipID,
                              SchoolID = a.SchoolID,
                              SchoolName = p.Name,
                              StudentCode = j.StudentCode,
                              Result = j.Result,
                          }).ToList();
            var model = listIn.OrderByDescending(x => x.SchoolID).ToList();
            var count = model.Count();
            ViewBag.listI = model1;
            return View(model);
        }

        public ActionResult Index()
        {

            var role = Convert.ToInt32(Session["Role"].ToString());
            // School
            if (role == 3)
            {
                var schoolID = Session["SchoolID"].ToString();
                var model = (from a in database.Intern
                             join b in database.Person on a.PersonID equals b.PersonID
                             join e in database.Organization on b.CompanyID equals e.ID
                             where b.SchoolID == schoolID && a.InternshipID == null
                             select new InternDatabase()
                             {
                                 PersonID = a.PersonID,
                                 FullName = b.LastName + " " + b.FirstName,
                                 Birthday = b.Birthday,
                                 Gender = b.Gender,
                                 Address = b.Address,
                                 Phone = b.Phone,
                                 Email = b.Email,
                                 Image = b.Image,
                                 CompanyID = b.CompanyID,
                                 CompanyName = e.Name,
                                 InternshipID = a.InternshipID,
                                 SchoolID = b.SchoolID,
                                 StudentCode = a.StudentCode,
                                 Result = a.Result,
                             }).OrderByDescending(x => x.CompanyID).ToList();
                var count = model.Count();
                return View(model);
            }
            else
            {
                return RedirectToAction("Index1");
            }
        }

        public List<InternShip> listIShip()
        {
            var personID = Session["Person"].ToString();
            var role = Convert.ToInt32(Session["Role"]);
            List<InternShip> model = new List<InternShip>();
            if (role == 4)
            {
                var mo = database.InternShip.Where(x => x.PersonID == personID).ToList();
                foreach (var item in mo)
                {
                    model.Add(item);
                }
            }
            else
            {
                var find = database.Person.Find(personID);
                var list = database.InternShip.Where(x => x.CompanyID == find.CompanyID);
                foreach (var item in list)
                {
                    model.Add(item);
                }
            }
            return model;
        }

        [HttpGet]
        public ActionResult Create()
        {
            var role = Convert.ToInt32(Session["Role"]);
            SetViewBag();
            SetViewBagS();
            SetViewBagG();
            if (role != 3)
            {
                SetViewBagI();
            }
            return View();
        }

        public void SetViewBag(string selectedID = null)
        {
            var list = database.Person.Where(x => x.RoleID == 2).ToList();
            List<Organization> Organ = new List<Organization>();
            foreach (var item in list)
            {
                var model = database.Organization.Find(item.CompanyID);
                Organ.Add(model);
            }
            SelectList OrganList = new SelectList(Organ, "ID", "Name");
            ViewBag.OrganList = OrganList;
        }

        public void SetViewBagS(string selectedID = null)
        {
            var list = database.Person.Where(x => x.RoleID == 3).ToList();
            List<Organization> Organ = new List<Organization>();
            foreach (var item in list)
            {
                var model = database.Organization.Find(item.SchoolID);
                Organ.Add(model);
            }
            SelectList SchoolList = new SelectList(Organ, "ID", "Name");
            ViewBag.SchoolList = SchoolList;
        }

        public void SetViewBagG(string selectedID = null)
        {
            SelectList GenGender = new SelectList(new[] {
                new {Text = "Nam", Value = true},
                new {Text = "Nữ", Value = false},
            }, "Value", "Text");
            ViewBag.GenGender = GenGender;
        }

        public void SetViewBagI(string selectedID = null)
        {
            var role = Convert.ToInt32(Session["Role"]);
            var list = new List<InternShip>();
            if (role == 4)
            {
                var per = Session["Person"].ToString();
                list = database.InternShip.Where(x => x.PersonID == per).ToList();
            }
            else
            {
                var companyID = Session["CompanyID"].ToString();
                list = database.InternShip.Where(x => x.CompanyID == companyID).ToList();
            }
            SelectList IList = new SelectList(list, "InternshipID", "CourseName");
            ViewBag.IList = IList;
        }

        public List<Internshipclass> listInternship()
        {
            var role = Convert.ToInt32(Session["Role"]);
            var model = new List<Internshipclass>();
            if (role == 3)
            {
                var schoolID = Session["SchoolID"].ToString();
                //var company = database.Person.Where(x => x.SchoolID == schoolID && x.RoleID == 5).ToList();
                //// lấy danh sách Thực tập sinh của trường
                //List<string> com = new List<string>();
                //foreach (var item in company)
                //{
                //    com.Add(item.CompanyID);
                //}
                //// Lấy danh sách Công ty mà tất cả thực tập sinh đang thực tập
                //IEnumerable<string> comp = com.Distinct();
                //// Xóa các công ty bị lập lại
                //List<InternShip> ListInternShip = new List<InternShip>();
                //foreach (var item in comp)
                //{
                //    var list = database.InternShip.Where(x => x.CompanyID == item).ToList();
                //    ListInternShip.InsertRange(ListInternShip.Count, list);
                //}
                // Lấy danh sách InternShip của  các công ty

                var list = (from a in database.Person
                            join c in database.Intern on a.PersonID equals c.PersonID
                            join b in database.InternShip on c.InternshipID equals b.InternshipID
                            join d in database.Organization on b.CompanyID equals d.ID
                            where a.SchoolID == schoolID && a.RoleID == 5
                            select new Internshipclass()
                            {
                                InternshipID = b.InternshipID,
                                CourseName = b.CourseName,
                                PersonID = b.PersonID,
                                FullName = a.LastName + " " + a.FirstName,
                                CompanyID = b.CompanyID,
                                Name = d.Name,
                                StartDay = b.StartDay,

                            }).OrderByDescending(x => x.StartDay).ToList();
                var list1 = new List<Internshipclass>();
                var idin = list[0].InternshipID;
                list1.Add(list[0]);
                for (int i = 0; i < list.Count(); i++)
                {
                    if (idin != list[i].InternshipID)
                    {
                        if (list1.Contains(list[i]) == false)
                        {
                            list1.Add(list[i]);
                            idin = list[i].InternshipID;
                        }
                    }
                }
                model = list1.ToList();
            }
            else
            {
                if (role == 2)
                {

QLThucTapSinh/QLThucTapSinh/Views/QLIntern/CVIntern.cshtml
@{
    ViewBag.Title = "CVIntern";
    Layout = "~/Views/Shared/_Layout1.cshtml";
    var testResults = (List<QLThucTapSinh.Common.TestResultsClass>)ViewBag.listI;
}
@model QLThucTapSinh.Models.Person
<link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<link href="~/Content/Home/styleCV.css" rel="stylesheet" />
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<body>
    <div class="container">
        <div>
            <h1>Thông tin của thực tập sinh</h1>
            <div class="circle">
                <div class="img">
                    <img src="@Model.Image" />>
                </div>

                <article class="name">
                    <div class="name3">
                        <div><p>Họ và Tên :</p></div>
                        <div><p>Giới Tính  :</p></div>
                        <div><p>	Tuổi   :</p></div>
                        <div><p>Địa Chỉ:</p></div>
                        <div><p>	Email  :</p></div>
                        <div><p> School :</p></div>

                    </div>
                    <div class="name4">
                        <div><p>@Model.LastName @Model.FirstName</p></div>
                        <div>
                            @if (Model.Gender == true)
                            {
                                <p class="text-list1">Nam</p>
                            }
                            else
                            {
                                <p class="text-list1" >Nữ</p>
                            }
                        </div>
                        <div><p>@Html.FormatValue(@Model.Birthday, "{0:dd/MM/yyyy}")</p></div>
                        <div><p>@Model.Address</p></div>
                        <div><p>	@Model.Email</p></div>
                        <div><p>Đại Học Duy Tân</p></div>
                    </div>
                </article>

            </div>
            <h1 class="classh1">Kết quả kiểm tra của thực tập sinh</h1>
            <div class="rank">
                <ul>
                    @{int id = 1; }
                    @foreach (var item in testResults)
                    {
                        var dem = id;
                        <li>
                            <span class="number">@dem</span>
                            <span class="name">@item.TaskName</span>
                            <span class="points">@item.Answer</span>
                            <span class="badge"></span>
                        </li>
                        id++;
                    }


                </ul>
            </div>
        </div>

</body>

QLThucTapSinh/QLThucTapSinh/Views/QLIntern/Create.cshtml
@model QLThucTapSinh.Common.InternDatabase

@{
    ViewBag.Title = "Create Intern";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<h2 class="text-primary" style="text-align:center">Thêm mới Thực tập sinh</h2>

@using (Html.BeginForm("Create", "QLIntern", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @if (@Session["Role"].ToString() == "3")
        {
            <div class="form-group">
                @Html.LabelFor(model => model.StudentCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StudentCode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StudentCode, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "datepicker form-control", style = "margin-left: 0px;width:20% !important;" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.DropDownList("Gender", (IEnumerable<SelectListItem>)ViewBag.GenGender, "--Select Gender--",
                   htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>


        @if (@Session["Role"].ToString() == "3")
        {
            <div class="form-group">
                @Html.LabelFor(model => model.CompanyID, "CompanyID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CompanyID", (IEnumerable<SelectListItem>)ViewBag.OrganList, "--Select Company--", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CompanyID, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                @Html.LabelFor(model => model.InternshipID, "InternshipID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("InternshipID", (IEnumerable<SelectListItem>)ViewBag.IList, "--Chọn Khóa học--", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.InternshipID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SchoolID, "SchoolID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SchoolID", (IEnumerable<SelectListItem>)ViewBag.SchoolList, "--Select School--", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SchoolID, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script src="https://kit.fontawesome.com/e00695e77f.js"
        crossorigin="anonymous"></script>
<script src="../Scripts/HomeControl/jquery-3.4.1.min.js"></script>
<script src="http://localhost:57770/Scripts/popper.min.js"></script>
<script src="http://localhost:57770/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<script src="../Scripts/HomeControl/index1.js"></script>

QLThucTapSinh/QLThucTapSinh/Views/QLIntern/Create1.cshtml
@model QLThucTapSinh.Models.Intern

@{
    ViewBag.Title = "Create1";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Create1</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Intern</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PersonID, "PersonID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InternshipID, "InternshipID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("InternshipID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InternshipID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Result, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Result, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Result, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QLThucTapSinh/QLThucTapSinh/Views/QLIntern/Edit.cshtml
@model QLThucTapSinh.Common.InternDatabase

@{
    ViewBag.Title = "Edit Intern";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<h2 class="text-primary" style="text-align:center">CẬP NHẬT THÔNG TIN</h2>

@using (Html.BeginForm("Edit", "QLIntern", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.PersonID)

    <div class="form-group">
        @Html.LabelFor(model => model.StudentCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StudentCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StudentCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "datepicker form-control", style = "margin-left: 0px;width:20% !important;" } })
            @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.DropDownList("Gender", (IEnumerable<SelectListItem>)ViewBag.GenGender, "--Select Gender--",
               htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CompanyID, "CompanyID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CompanyID", (IEnumerable<SelectListItem>)ViewBag.OrganList, "--Select Company--", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CompanyID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script src="https://kit.fontawesome.com/e00695e77f.js"
        crossorigin="anonymous"></script>
<script src="../Scripts/HomeControl/jquery-3.4.1.min.js"></script>
<script src="http://localhost:57770/Scripts/popper.min.js"></script>
<script src="http://localhost:57770/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<script src="~/Scripts/HomeControl/index1.js"></script>

QLThucTapSinh/QLThucTapSinh/Views/QLIntern/imPortExcel.cshtml
@{
    ViewBag.Title = "imPortExcel";
    Layout = "~/Views/Shared/_Layout1.cshtml";
    var School = (List<QLThucTapSinh.Models.Organization>)ViewBag.ListSchool;
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
    <link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
</head>
<body>
    <section>
        <H2 style="color: #007bff!important;">Hướng dẫn  import file excel:</H2>
        <ol>
            <li style="    color: red;display: inline-grid;margin-bottom: 42px;">
                1:Tạo 1 file excel theo form như sau  :
                <img style="width:81%;" src="~/img/file excel/excel1.png" alt="Alternate Text" />
            </li>
            <li style=" color: red; margin-bottom: 42px; display: inline-grid">
                2 : trỏ để lưu vào ổ D:
                <img style="width:81%" src="~/img/file excel/excel2.jpg" alt="Alternate Text" />
            </li>
            <li style="color: red;display: inline-grid;margin-bottom: 42px; ">
                3 :trỏ để lưu file vào ổ D:
                <img style="width:81%" src="~/img/file excel/excel3.jpg" alt="Alternate Text" />
            </li>
        </ol>
    </section>

    <section>
        @using (Html.BeginForm("imPortExcel", "QLIntern", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.Raw(ViewBag.Error)
            <br />
            <h1 style="color: #007bff!important;">Chọn File Excel: </h1>
            <input type="file" name="excelfile" value="Chọn file" />
            <br />
            <h2 style="color: #007bff!important;">Nhấn submit để chọn  import vào:</h2>
            if (Session["Role"].ToString() == "3")
            {
                <select name="organID">
                    @foreach (var item in School)
                    {
                        <option value="@item.ID">@item.Name</option>
                    }
                </select>
            }
            <br />
            <input type="submit" name="Import" />

        }
    </section>
</body>