QLThucTapSinh/QLThucTapSinh/Controllers/QLSchoolController.cs
using PagedList;
using QLThucTapSinh.Common;
using QLThucTapSinh.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace QLThucTapSinh.Controllers
{
    public class QLSchoolController : Controller
    {
        SQLThucTapSinhEntities database = new SQLThucTapSinhEntities();

        // GET: QLSchool
        public ActionResult Index()
        {
            var modle = new Share().listOrgan(3).OrderByDescending(x => x.StartDay).ToList();
            SetViewBagM();
            return View(modle);
        }

        public void SetViewBagM(string selectedID = null)
        {
            SelectList Month = new SelectList(new[] {
                new {Text = "Một Tháng", Value = 1},
                new {Text = "Ba Tháng", Value = 3},
                new {Text = "Sáu Tháng", Value = 6},
                new {Text = "Một Năm", Value = 12},
            }, "Value", "Text");
            ViewBag.Month = Month;
        }

        [HttpPost]
        public JsonResult ChangeStatus(string id)
        {
            var res = new Share().ChangeStatus(id, 3);
            return Json(new
            {
                status = res
            });
        }

        public bool extension(string id, int val)
        {
            try
            {
                var model = database.Organization.Find(id);
                if (model.Status == true)
                {
                    model.ExpiryDate += +val;
                }
                else
                {
                    model.StartDay = DateTime.Now;
                    model.ExpiryDate = val;
                    model.SendEmail = false;
                    new Share().ChangeStatus(id, 3);
                }
                database.SaveChanges();
                return true;
            }
            catch
            {
                return false;
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Organization organization)
        {
            if (ModelState.IsValid)
            {
                CompanyAndSchool organ = new CompanyAndSchool();
                if (organ.Create(organization, 3))
                {

                    var modle = new Share().listOrgan(3).OrderByDescending(x => x.StartDay).ToList();
                    var comid = modle[0].ID;
                    var find = database.Person.SingleOrDefault(x => x.SchoolID == comid);
                    SendMailTK(find.PersonID);
                    return RedirectToAction("Index", modle);
                }
                else
                {
                    ModelState.AddModelError("", "Thêm Công ty thất bại");
                }
            }
            return View("Create");
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            var model = database.Organization.Find(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Organization organi)
        {
            if (ModelState.IsValid)
            {

                var model1 = new CompanyAndSchool().Update(organi);
                if (model1)
                {
                    var modle = new Share().listOrgan(3).OrderByDescending(x => x.StartDay).ToList();
                    return RedirectToAction("Index", modle);
                }
                else
                {
                    ModelState.AddModelError("", "Cập nhật thất bại");
                }
            }
            return View("Edit");
        }

        public ActionResult Delete(string id)
        {
            var find = database.Person.SingleOrDefault(x => x.SchoolID == id && x.RoleID == 3);
            if (database.Users.SingleOrDefault(x => x.PersonID == find.PersonID) != null)
            {
                database.Users.Remove(database.Users.SingleOrDefault(x => x.PersonID == find.PersonID));
            }
            database.Person.Remove(find);
            var model = database.Organization.Find(id);
            database.Organization.Remove(model);
            database.SaveChanges();
            var model1 = database.Organization.OrderByDescending(x => x.StartDay).ToList();
            return RedirectToAction("Index", model1);
        }

        public bool SendMailTK(string personID)
        {
            try
            {
                var res = database.Person.Find(personID);
                string cus = res.LastName + " " + res.FirstName;
                var com = database.Organization.Find(res.SchoolID);
                string compa = com.Name;
                string email = res.Email;
                string nd = personID;
                string content = System.IO.File.ReadAllText(Server.MapPath("~/Email/TaiKhoan.html"));
                content = content.Replace("{{CustomerName}}", cus);
                content = content.Replace("{{CompanyName}}", compa);
                content = content.Replace("{{noidung}}", nd);

                var fromEmailAddress = ConfigurationManager.AppSettings["FromEmailAddress"].ToString();
                var fromEmailPassword = ConfigurationManager.AppSettings["FromEmailPassword"].ToString();
                var smtpHost = ConfigurationManager.AppSettings["SMTPHost"].ToString();

                MailMessage message = new MailMessage(fromEmailAddress, email);
                message.Subject = "Thông báo Đăng ký Tài khoản";
                message.IsBodyHtml = true;
                message.Body = content;

                SmtpClient client = new SmtpClient(smtpHost, 587);
                client.EnableSsl = true;
                client.Timeout = 100000;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                NetworkCredential nc = new NetworkCredential(fromEmailAddress, fromEmailPassword);
                client.UseDefaultCredentials = false;
                client.Credentials = nc;
                client.Send(message);
                return true;
            }
            catch
            {
                return false;
            }
        }


    }
}

QLThucTapSinh/QLThucTapSinh/Controllers/TestController.cs
using PagedList;
using QLThucTapSinh.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLThucTapSinh.Controllers
{
    public class TestController : Controller
    {

        SQLThucTapSinhEntities database = new SQLThucTapSinhEntities();
        public ActionResult Index( string search,int page = 1, int pageSize = 5)
        {
            IQueryable<Task> model = database.Task.Where(x=>x.PersonID == "ZXCKBHML");
            if (!string.IsNullOrEmpty(search))
            {
                model = model.Where(x=>x.TaskName.Contains(search)||x.Note.Contains(search));
            }

            var model1 = model.OrderBy(x => x.TaskID).ToPagedList(page, pageSize);
            ViewBag.ChuoiTimKiem = search;
            return View(model1);
        }


        public ActionResult Testing(string search = "")
      {
            var model = database.Task.Where(x => x.TaskName.Contains(search)).OrderBy(x => x.TaskID).ToPagedList(1, 5);
            var count = model.Count();
            return PartialView(model);
        }

    }
}

QLThucTapSinh/QLThucTapSinh/Views/QLSchool/Create.cshtml
@model QLThucTapSinh.Models.Organization
@{
    Layout = null;
}
<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
@*<script src="~/Scripts/jquery-3.4.1.min.js"></script>*@
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
@using (Html.BeginForm())
{


    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" }, id = "xFilePath" })
            <a id="SelectImage" onclick="BrowseServer()" href="#">Chọn ảnh</a>
            @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" }, id = "xFilePath1" })
            <a id="SelectLogo" onclick="Browse()" href="#">Chọn ảnh</a>
            @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDay, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDay, new { htmlAttributes = new { @class = "datepicker" } })
            @Html.ValidationMessageFor(model => model.StartDay, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ExpiryDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ExpiryDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ExpiryDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
            <input type="reset" value="Reset" class="btn btn-primary" />
        </div>
    </div>
}
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<link href="~/Content/font-awesome.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<script src="/Scripts/Plugins/ckfinder/ckfinder.js"></script>


<script>
    $(function () {
        $('.datepicker').datepicker({
            dateFormat: "dd-mm-yy",
            changeMonth: true,
            changeYear: true,
            showOn: "both",
            buttonText: "<i class='fa fa-calendar'></i>"
        });
    });
    function BrowseServer() {
        // You can use the "CKFinder" class to render CKFinder in a page:
        var finder = new CKFinder();
        finder.basePath = '~/ckfinder';	// The path for the installation of CKFinder (default = "/ckfinder/").
        finder.selectActionFunction = SetFileField;
        finder.popup();
    }
    // This is a sample function which is called when a file is selected in CKFinder.
    function SetFileField(fileUrl) {
        document.getElementById('xFilePath').value = fileUrl;
    }

    function Browse() {
        // You can use the "CKFinder" class to render CKFinder in a page:
        var finder = new CKFinder();
        finder.basePath = '~/ckfinder';	// The path for the installation of CKFinder (default = "/ckfinder/").
        finder.selectActionFunction = SetFileField1;
        finder.popup();
    }
    // This is a sample function which is called when a file is selected in CKFinder.
    function SetFileField1(fileUrl) {
        document.getElementById('xFilePath1').value = fileUrl;
    }
</script>

QLThucTapSinh/QLThucTapSinh/Views/QLSchool/Edit.cshtml
@model QLThucTapSinh.Models.Organization
@{
    ViewBag.Title = "Update School";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<h2 class="text-primary" style="text-align:center">Cập nhật thông tin Nhà trường</h2>

@using (Html.BeginForm("Edit", "QLSchool", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" }, id = "xFilePath" })
                <a id="SelectImage" onclick="BrowseServer()" href="#">Chọn ảnh</a>
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" }, id = "xFilePath1" })
                <a id="SelectLogo" onclick="Browse()" href="#">Chọn ảnh</a>
                @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-outline btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QLThucTapSinh/QLThucTapSinh/Views/QLSchool/Index.cshtml
@{
    ViewBag.Title = "Quản lý Nhà trường";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}


@using QLThucTapSinh.Models;
@model List<QLThucTapSinh.Models.Organization>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
<link href="~/Content/Quanli/style.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/Plugins/jquery-1.10.2.js")" type="text/javascript"></script>
<script src="~/Scripts/Controller/SchoolController.js"></script>
<div class="text-primary" style="text-align:center"> DANH SÁCH NHÀ TRƯỜNG</div>
<h1 class="page-header">
    <a href="/QLSchool/Create" class="btn btn-outline btn-primary">Thêm</a>
</h1>
<input class="form-control" id="myInput" type="text" placeholder="Search..">
<div class="dataTable_wrapper">
    <table class="table table-striped table-bordered table-hover" id="table">
        <thead>
            <tr>
                <th class="th">Nhà trường</th>
                <th class="th">Địa chỉ</th>
                <th class="th">Điện thoại</th>
                <th class="th">Email</th>
                <th class="th">Ngày bắt đầu</th>
                <th class="th">Trạng thái</th>
                <th class="th">Gia hạn</th>
                <th class="th">Hoạt động</th>
            </tr>
        </thead>
        <tbody id="myTable">
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Address</td>
                    <td>@item.Phone</td>

                    <td>@item.Email</td>
                    <td>@Html.FormatValue(@item.StartDay, "{0:dd/MM/yyyy}")</td>
                    <td>
                        @if (item.Status == true)
                        {<a href="#" class="btn-active" data-id="@item.ID">Kích hoạt </a>}
                        else
                        { <a href="#" class="btn-active" data-id="@item.ID">Khóa </a>}
                    </td>

                    <td style="" class="idSort" data-ids="@item.ID">
                        @Html.DropDownList("Gender", (IEnumerable<SelectListItem>)ViewBag.Month, "Chọn tháng", htmlAttributes:
                        new { @class = "gender " })
                    </td>

                    <td>
                        <a href="/QLSchool/Edit/@item.ID" class="btn btn-outline btn-primary">Sửa</a> ||
                        <a href="/QLSchool/Delete/@item.ID" class="btn btn-outline btn-primary">Xóa</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>